### ISSUE TITLE
Support checking consistency across the variable hierarchy

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#127]
There is a use case for checking consistency across the variable hierarchy (or for computing variables higher-up in the hierarchy automatically from its components).

Aggregation along the variable hierarchy and checking consistency is already supported by the pyam methods [`aggregate()`](https://pyam-iamc.readthedocs.io/en/stable/api/iamdataframe.html#pyam.IamDataFrame.aggregate) and [`check_aggregate()`](https://pyam-iamc.readthedocs.io/en/stable/api/iamdataframe.html#pyam.IamDataFrame.check_aggregate).

I propose to extend the variable-definitions for a nomenclature-compatible variable codelist by a two "standard" attributes:
- **components**: the list of variables that are components of the variable
- **check-aggregate**: takes a boolean on whether to perform the aggregate-check as part of the [`process()`](https://nomenclature-iamc.readthedocs.io/en/stable/api.html#nomenclature.process) function

An example of the configuration:
```yaml
- Emissions|CO2|Energy and Industrial Processes:
    description: CO2 emissions from the energy and industry sectors
    unit: Mt CO2
    components:
      - Emissions|CO2|Energy
      - Emissions|CO2|Emissions|CO2|Industrial Processes 
    check-aggregate: true
    <other attribute>: Some text, value, boolean or list (optional)
```

*Note*: the **pyam** methods `aggregate()` and `check_aggregate()` interpret `components=None` as "all variables one level below the variable to be aggregated" and automatically detects all these variables.

*Note: Computing aggregates will be tackled as a subsequent issue.*

@volker-krey @christophbertram @lolow

**Comment by christophbertram** [comment]
It would be good to design this from the start with the functionality of adding more than one list of components, e.g. for Final Energy having both the components 
> Final Energy|Transport
> Final Energy|Buildings
> Final Energy|Industry
as well as the alternative components
> Final Energy|Electricity
> Final Energy|Liquids
> Final Energy|Gases
> Final Energy|Solids
> Final Energy|Other
The check-aggregate would potentially also be activated only for one list.

**Comment by lolow** [comment]
Should it be done using 1 unique entry for the variable or using multiple:

unique entry:
```yaml
- Final Energy:
    description: Total final energy consumption by all end-use sectors and all fuels,
      excluding transmission/distribution losses
    unit: [EJ/yr, GWh]
    components: 1
      subcomponents:
        - Final Energy|Transport
        - Final Energy|Buildings
        - Final Energy|Industry
      check-aggregate: true
    components: 2
      subcomponents:
        - Final Energy|Electricity
        - Final Energy|Liquids
        - Final Energy|Gases
        - Final Energy|Solids
        - Final Energy|Other
      check-aggregate: true
``` 
multiple:
```yaml
- Final Energy:
    description: Total final energy consumption by all end-use sectors and all fuels,
      excluding transmission/distribution losses
    unit: [EJ/yr, GWh]
    components:
      - Final Energy|Transport
      - Final Energy|Buildings
      - Final Energy|Industry
    check-aggregate: true
- Final Energy:
    description: Total final energy consumption by all end-use sectors and all fuels,
      excluding transmission/distribution losses
    unit: [EJ/yr, GWh]
    components:
      - Final Energy|Electricity
      - Final Energy|Liquids
      - Final Energy|Gases
      - Final Energy|Solids
      - Final Energy|Other
    check-aggregate: true
```

**Comment by lolow** [comment]
or with better naming:

```yaml
- Final Energy:
    description: Total final energy consumption by all end-use sectors and all fuels,
      excluding transmission/distribution losses
    unit: [EJ/yr, GWh]
    aggregation: 1
      components:
        - Final Energy|Transport
        - Final Energy|Buildings
        - Final Energy|Industry
      check-aggregate: true
    aggregration: 2
      components:
        - Final Energy|Electricity
        - Final Energy|Liquids
        - Final Energy|Gases
        - Final Energy|Solids
        - Final Energy|Other
      check-aggregate: true
```
