### ISSUE TITLE
Check that weight variables exist

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/nomenclature#132]
We want to verify that the variable values provided as a `weight` argument for weighted aggregation are present in the variable list as their own entries.
For example a variable defined like this:

```yaml
- Food Demand:
    unit: kcal/cap/day
    weight: Population
```

would need a entry for `Population`, e.g.:

```
- ...
- Population:
    unit: million
- ...
```

Currently, as far as I'm aware, this is not being checked.
