### ISSUE TITLE
RegionProcessor "native-region-rename" drops mappings

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#203]
While toiling away at the GAINS-linkage workflow, I noticed some unexpected behavior of the nomenclature package.

For GAINS, we need to map model-native regions in a 1-to-n-manner: the values for the MESSAGE region WEU have to be copied/renamed to the GAINS regions Austria, Germany, etc., so the resulting dataframe must have ~181 regions from the MESSAGE-native 11.

My initial plan was to simply use the native-region mappings, see https://github.com/iiasa/engage-gains-mapping/blob/main/mappings/MESSAGE_v1.1.yaml

# Unexpected behavior

The attribute `RegionAggregationMapping.rename_mapping` (see [here](https://github.com/IAMconsortium/nomenclature/blob/57b08f759d7a5ec7e2129355196164d96810ab6d/nomenclature/processor/region.py#L270) only has a single mapping for each native-region.

# Solution 1:

Add a dedicated validation that the section "native_regions" must have unique keys (to avoid misunderstandings like mine in the future), and use the "common-region" section for the GAINS-mapping.

# Solution 2:

Refactor the `rename_mapping` attribute such that it is either a mapping "str->str" if unique or a mapping "str -> list[str]" otherwise (and also refactor the `RegionProcessor.apply` method)...

Any thoughts, @phackstock @peterkolp?

**Comment by danielhuppmann** [comment]
After thinking about this for for an afternoon, I think that option 1 makes a lot more sense, so I refactored the engage-gains-mapping via https://github.com/iiasa/engage-gains-mapping/pull/4

**Comment by phackstock** [comment]
Good question @danielhuppmann, I've though about it for a while and I think your original solution with:

```yaml
model:
  - MESSAGEix-GLOBIOM 1.1
native_regions:
  - ...
  - MESSAGEix-GLOBIOM 1.1|Latin America and the Caribbean: CARB_WHOL
  - MESSAGEix-GLOBIOM 1.1|Latin America and the Caribbean: CEAM_WHOL
  - MESSAGEix-GLOBIOM 1.1|Latin America and the Caribbean: CHIL_WHOL
```

would have actually worked just not in the way you were probably expecting. 

I created a quick test locally with a super simple mapping:

```yaml
model: test
native_regions:
  - region_1: Region_1
  - region_1: Region 1
```

which after reading in with `RegionAggregationMapping.from_file("mapping_file.yaml")`, I got this:

```console
[NativeRegion(name='region_1', rename='Region_1'), NativeRegion(name='region_1', rename='Region 1')]
```

In other words, the parsing right now is relatively dumb as it just creates one native region per list entry. It does not check if a region appears multiple times to combine the rename attribute. That being said, I think it should work though with your original approach as well. Did you check that the renaming applied to input data drops the desired regions?

**Comment by danielhuppmann** [comment]
> Did you check that the renaming applied to input data drops the desired regions?

Yes, only one renaming "survives" because the `rename_mapping` attribute creates a dictionary and thereby does condenses to a unique value for each key (not multiple target values).
See https://github.com/IAMconsortium/nomenclature/blob/57b08f759d7a5ec7e2129355196164d96810ab6d/nomenclature/processor/region.py#L270

**Comment by phackstock** [comment]
Ah yes of course, sorry for not catching that. Ok then we should definitely do something about it as this is for sure undesired behavior. 
I agree with you that we should definitely do something about it. The smallest possible change I suppose would be a validator in `RegionAggregationMapping` to check that the native regions are unique and throw an error if they are not. 
Then again, the use case for renaming a single native region to multiple different names clearly exists. 
Maybe we should modify `rename_mapping` then to allow for the original way in which the model mapping was defined.

Maybe we should (also) allow the following then:

```yaml
name: model1
native_regions:
  - region_1:
    - Region1
    - Region 1
  - region_2 ...
```
if we go for that I would suggest that we enforce this way only, this:

```yaml
name: model1
native_regions:
  - region_1: Region1
  - region_1: Region 1
```

should no longer be allowed.

Alternatively, we could also keep it as is and tell people in the docs that if this kind of renaming is required they have to use `common_regions`. However, that might be confusing with regards to the name `common_regions`.
