### ISSUE TITLE
Reading complex attributes from Excel

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/nomenclature#220]
This issues addresses the first problem mentioned in #217.
Any codelist entry that is more complex than a mapping to a single value, e.g. `region-aggregation` in:

```yaml
- Price|Carbon:
    definition: Price of carbon (as reported by the model)
    unit: US$2010/t CO2
    region-aggregation:
        - Price|Carbon (mean):
            method: mean
```

will be exported to Excel using `CodeList.to_excel` in the following way:

| Variable      |                 Description                | Unit          | Region-aggregation                             |   |   |
|---------------|:------------------------------------------:|---------------|------------------------------------------------|---|:-:|
| Price\|Carbon | Price of carbon (as reported by the model) | US$2010/t CO2 | [{'Price\|Carbon (mean)': {'method': 'mean'}}] |   |   |

when reading it back from the Excel file into a `CodeList` we get an error as the string under _Region-aggregation_ cannot be interpreted as the structure above.

This should be fixable by using json serialization. Any attribute value that is a list or a dict, should be serialized as json during `CodeList.to_pandas`. As it is read it again using a pydantic pre validator on those fields the values can be read again correctly.
FYI @byersiiasa
