### ISSUE TITLE
to_yaml does not indent lists

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/nomenclature#222]
Discovered during 218, reading a yaml file into a `CodeList` object and dumping it out to yaml again does not work for nested structures.

As an example a variable code list with a _region-aggregation_ attributes:

```yaml
- Price|Carbon:
    definition: Price of carbon (as reported by the model)
    unit: US$2010/t CO2
    region-aggregation:
        - Price|Carbon (mean):
            method: mean
```

reading it in and writing it out to yaml again:

```python
VariableCodeList.from_directory("variable", "definitions").to_yaml()
```

gives the following:

```yaml
Price|Carbon:
    description: Price of carbon (as reported by the model)
    unit: US$2010/t CO2
    region_aggregation:
    - Price|Carbon (mean):
        method: mean
```

The indentation under region_aggregation is missing which breaks reading the yaml file.

It seems that this is a known issue with pyyaml (https://github.com/yaml/pyyaml/issues/234 and https://stackoverflow.com/questions/25108581/python-yaml-dump-bad-indentation) so it shouldn't be too hard to fix.
