### ISSUE TITLE
Filter CodeLists by any attribute

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#233]
Building on #226, we should now extend the `filter()` method and make it usable for any **CodeList** instance (not just **RegionCodeList**).

The use case that I have in mind is filtering a list of variables to have only those that are *required*, e.g. that have an attribute like
```yaml
- Final Energy|Electricity:
    description: Final energy consumption of electricity (including on-site solar
      PV), excluding transmission/distribution losses
    unit: EJ/yr
    required: true
```

See a real-world use case [here](https://github.com/iiasa/engage-gains-mapping/blob/ccb1cfd237a021ac0df1f37dae67a8fef5a4df42/definitions/variable/variable.yaml#L39).
