### ISSUE TITLE
Use schema validation for nomenclature definitions

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#24]
Seeing the nice implementation by @phackstock of the model-region-configuration parsing in #22 gave me two ideas how to improve the structure for variables and regions:

1. Implement a schema validation of the yaml files
2. Change the structure of the definitions files from a simple dictionary
```yaml
Primary Energy:
  definition: Total primary energy consumption
  unit: EJ/yr
```
to a list of dictionaries:
```yaml
- Primary Energy:
    definition: Total primary energy consumption
    unit: EJ/yr
```
This would allow to safeguard against duplicate entries within one file (where all identical entries except for the last one would currently be simply ignored).
