### ISSUE TITLE
MetaCode brainstorming

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/nomenclature#241]
Following our discussion earlier, I'm sketching out some ideas for a `MetaCodeList`.
I think it's easiest to start at what the yaml file is supposed to look like:

```yaml
- Meta category with boolean values:
  allowed_values: [true, false]
  default: false
- Meta category for tracking versions:
  data_type: int
  required: true
- Meta category only required for Downscaling:
  apply_to: "Downscaling*"
  required: True
```

the three above examples illustrate some of the use cases that I can see, listing them in order:
1. _Meta category with boolean values_ has allowed values `true` and `false`, defaulting to `false`
2. _Meta category for tracking versions_ is required and requires an integer. Allowed values not really make sense here since we expect increasing integer numbers.
3. _Meta category only required for Downscaling_ should only be applied to models matching the pattern `Downscaling*`, in which case, however, it is required.

Looking at this again @danielhuppmann I'll retract my previous suggestion of making the entries in `allowed_values` `MetaCodes` as that seems too complicated and not every entry in the sample `MetaCodeList` even features `allowed_values`.

It's probably better to translate the above structure into something like:

```python
class MetaCode(Code):
    allowed_values: Optional(list[any])
    default: Optional(any)
    data_type: Optional(type)
    required: Optional(bool)
```

then we'd have a `MetaCodeList` to hold a list of `MetaCodes`.
