### ISSUE TITLE
Check for collision within a set of region mappings

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/nomenclature#25]
Building on #22, one of the next steps in verification is to check that there are no collisions within all of the provided mappings. 
Illustration of one failure scenario:
Given `mapping_1`:
```yaml
name: model_1
native_regions:
  - native_region_a: alternative_name
```
`mapping_2`:
```yaml
name: model_2
native_regions:
  - alternative_name
```
Alternatively it could also be that in `mapping_2` we have a region called `native_region_b` which we end up renaming `alternative_name`.
In any case a next step in region mapping could be to check for this.
@danielhuppmann, @peterkolp is this really an issue or is this actually fine? If it is fine, feel free to close the issue. If it is something that should be checked are there any other failure scenarios that should be checked? For the common regions it is of course expected that they share the same name.
