### ISSUE TITLE
Potential conflicts with overlapping region-aggregation instructions

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#290]
It's not clear how the following configuration would work:

```yaml
- Price|Carbon:
    description: Price of carbon (as reported by the model)
    unit: USD_2010/t CO2
    region-aggregation:
      - Price|Carbon (mean):
          method: mean
- Price|Carbon (mean):
    description: Price of carbon (computed as unweighted mean across regions)
    unit: USD_2010/t CO2
```

In particular, if a scenario has data for the variable "Price|Carbon (Mean)" at a native-region resolution, which of two instructions (aggregation from "Price|Carbon" or from "Price|Carbon (Mean)") would take priority?
