### ISSUE TITLE
Mix multiple external repos in a single dimension

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/nomenclature#295]
The following use case is currently not supported. 
Import **multiple** external repositories into the **same** definition dimension:

```yaml
repositories:
  common-definitions:
    url: https://github.com/iamconsortium/common-definitions
  legacy-definitions:
    url: https://github.com/iamconsortium/common-definitions
definitions:
  variable:
    repository: [common-definitions, legacy-definitions]
```
