### ISSUE TITLE
Double stacking external repos does not work as expected

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/nomenclature#316]
I just ran into this potential issue when trying to create a DataStructure definition based of off legacy definitions.
What I did is:
1. Create a new (local) repository with an empty definitions folder and a `nomenclature.yaml` file with the following entry:
```yaml
repositories:
  legacy-definitions:
    url: https://github.com/IAMconsortium/legacy-definitions.git/
definitions:
  variable:
    repository: legacy-definitions
```
2. Since common definitions, as of right now (https://github.com/IAMconsortium/legacy-definitions/blob/main/nomenclature.yaml) contains a `nomenclature.yaml` file itself I thought that the above configuration should import common-definitions as well. However common-definitions was not fetched and instead just the yaml files from legacy-definitions were read.

I would see two ways to fix this, one easy one slightly more involved (because recursion).

### Option 1 (the quick fix)

Disallow any external repo to have a `nomenclature.yaml` on its own. This is easy enough to check and we would simply throw an error if this occurs.

### Option 2 (recursion)

We allow, potentially arbitrary many times, stacking of external repos. 

My preferred option would be 1. No only because it is faster to implement but also because the use case 2 currently does not exist and I'm not sure we even want to allow it for the sake of keeping things flat and easy ( "*Flat is better than nested.*" from https://peps.python.org/pep-0020/). 

What are your thoughts on the matter @danielhuppmann?
