### ISSUE TITLE
Using only country in nomenclature config breaks CodeList

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/nomenclature#319]
I saw this in https://github.com/iiasa/openmod4africa-workflow, where the latest nomenclature update in combination with a nomenclature config where in the region dimension there's only the country attribute:

```yaml
repositories:
  openENTRANCE:
    url: https://github.com/openENTRANCE/openentrance
definitions:
  variable:
    repository: openENTRANCE
  region:
    country: true
```

It broke in the test here: https://github.com/iiasa/openmod4africa-workflow/actions/runs/7829213013/job/21360733654. 

Issue is that https://github.com/IAMconsortium/nomenclature/blob/86d38f9b4457f897445bee387554d35e45ae873e/nomenclature/codelist.py#L622 
attempts to iterate over the region.repositories attribute which is empty.
