### ISSUE TITLE
Use all attributes in tag-list

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#402]
Currently, the tag-processing in a code replaces the tag-name in a code-name or any attributes with the values of the matching attributes in the tag-item. However, if there are attributes in the tag-item that are not present in the code, these are ignored.

It would be helpful to also add these attributes as-is to the code.

A concrete example:
The code
```yaml
- Primary Energy|{Primary Fossil Fuel}:
     description: Primary energy consumption of {Primary Fossil Fuel}
     unit: EJ/yr
```

with the tag-list:
```yaml
- Primary Fossil Fuel:
    - Coal:
        description: coal
        info: Fossil fuels are bad.
```

currently yields
```yaml
- Primary Energy|Coal:
     description: Primary energy consumption of coal
     unit: EJ/yr
```

Instead, the expanded code should also have the *info* attribute.

**Comment by dc-almeida** [comment]
What would be the desired behaviour in cases of multiple tags in one item?

**Comment by danielhuppmann** [comment]
You mean
```yaml
- Primary Energy|{Primary Fossil Fuel}|{Source}:
     description: Primary energy consumption of {Primary Fossil Fuel}
     unit: EJ/yr
```
and both the Primary-Fossil-Fel and Source tag lists have an attribute `notes`... Good question.

Easiest would be to raise an error indicating a conflict, right? And require a "formal" solution like adding
```yaml
    notes: "{Primary Fossil Fuel} {Source}"
```
which would trigger the normal tag-replacement.
