### ISSUE TITLE
Make workflow.py obsolete for standard cases

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#405]
Most of the repository with a `workflow.py` file are very generic, see for example https://github.com/iiasa/prisma-workflow/blob/main/workflow.py.

This could be abstracted away by moving this into `nomenclature.yaml`, for example
```yaml
workflow:
    [definitions: "some-custom-definition-folder"[
    processors:
      - region-processor: "mappings"
      - [... ]
 ```

Not sure what the ideal entrypoint would be (from the scenario-processing side), maybe a new nomenclature-module that can be called if `workflow.py` doesn't exist?
