### ISSUE TITLE
Allow filtering of tag-lists

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#416]
Working with ever-longer lists of variables in the common-definitions repo, I'm wondering how to more efficiently structure the creation of combinations.

One idea is to add filters, e.g.
```yaml
- Secondary Energy|{Secondary Fuel Level 3|ccs true}:
     description: Production of {Secondary Fuel Level 3}
     ...
```
which would only take the elements from the tag-list that have an attribute `ccs: True`. Alternative simple filters would be tier- or level-attributes.

An alternative solution would be to add a dedicated filter-attribute, like
```yaml
- Secondary Energy|{Secondary Fuel Level 3}:
     tag-filter:
       - Secondary Fuel Level 3:
            ccs: True
     description: Production of {Secondary Fuel Level 3}
     ...
```

Any thoughts @phackstock @dc-almeida?
