### ISSUE TITLE
Allow wildcard-items in Code

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#432]
To allow more flexibility for reporting of technical parameters, we want to allow "wildcard-codes" echoing the wildcard-implementation in pyam using `*`.

Concept: a VariableCode can be defined as
```yaml
- Capital Cost|Electricity|Coal|*:
    description: Technology-specific capital cost of a newly installed plant to generate
      electricity from coal
    unit: USD_2010/kW
```

The validation-method should then accept any variable that matches the code-name including any string for the wildcard.

This can follow the implementation by @phackstock here
https://github.com/IAMconsortium/nomenclature/blob/f210213ccf51e8f70e70cd3e1715f273cb100f0c/nomenclature/config.py#L34

To be explicit, any of the following variables should pass validation:
- Capital Cost|Electricity|Coal|1
- Capital Cost|Electricity|Coal|Lignite
- Capital Cost|Electricity|Coal|Super-Critical 
- Capital Cost|Electricity|Coal|really dirty stuff

**Comment by danielhuppmann** [comment]
Maybe this was already implemented in #397, please double-check.

**Comment by dc-almeida** [comment]
Indeed I was checking that today with some tests, will confirm tomorrow

**Comment by danielhuppmann** [comment]
Follow-up because I did some tests myself: wildcard * in variable names work, but the units are not checked. Plus there may be some difficulties here because there may be multiple possibly matching VariableCode items for a variable, e.g.,

```yaml
- Capital Cost|Hydrogen|*:
    description: ...
    unit: USD_2010/kW
- Capital Cost|Hydrogen|Fossil*
    description: ...
    unit: EUR_2020/kW
```

Not saying that this makes sense, but if there is now a variable "Capital Cost|Hydrogen|Fossil|Coal" in an **IamDataFrame**, it's not clear which unit should apply...
