### ISSUE TITLE
Allow easier import of all NUTS regions

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#435]
I tried to use NUTS regions in production for iDesignRES and I have three requests for simpler use:

1. Allow wildcard-selection: currently a user has to list all ISO2 codes individiually. It would be better to allow a wildcard import like
    ```yaml
    region:
        nuts:
          nuts-1: "*"
          nuts-2: "*"
          nuts-3: "*"
    ```
2. It would be easier for working with NUTS regions in the Scenario Explorer if the NUTS-level would be part of the hierarchy, so rather than importing all NUTS-regions as "NUTS 2021-2024", please change that to "NUTS 1 regions (2021-2024)".
