### ISSUE TITLE
Allow easier setting of multiple warning levels for same criterion in `DataValidator`

### ISSUE THREAD

**Issue by dc-almeida** [IAMconsortium/nomenclature#439]
IIRC, one of the suggested improvements was to change the write-up of multiple warning levels for the same validation criterion.
E.g.: currently, one would write: 

```yaml
- variable: Primary Energy
   year: 2010
   upper_bound: 5
   lower_bound: 1
- variable: Primary Energy
   year: 2010
   upper_bound: 2.5
   lower_bound: 1
   warning_level: low
- variable: Primary Energy|Coal
   year: 2010
   upper_bound: 5
   lower_bound: 1
```

This would mean "Primary Energy" would have two levels of warnings, `error` (by default) and `low`. But for that, the `IamcDataFilter` attributes (in this case, `variable` and `year`) have to be repeated for each level.

How would a better write-up look like? I leave an example below:
```yaml
- variable: Primary Energy
  year: 2010
  warning_level:
    error:
      upper_bound: 5
      lower_bound: 1
    low:
      upper_bound: 2.5
      lower_bound: 1
- variable: Primary Energy|Coal
  year: 2010
  upper_bound: 5
  lower_bound: 1
```

In this case, I guess `error` could no longer be default, and would require quite a bit of refactoring.
Thoughts, @danielhuppmann @phackstock

**Comment by danielhuppmann** [comment]
I think this example makes sense. An alternative, as food for thought, would be more explicit

```yaml
- variable: Primary Energy
  year: 2010
  validation:
    - warning_level: error
      upper_bound: 5
      lower_bound: 1
    - warning_level: low
       upper_bound: 2.5
       lower_bound: 1
- variable: Primary Energy|Coal
  year: 2010
  upper_bound: 5
  lower_bound: 1
```

This might be easier to implement because "warning-level" attribute doesn't have to be abused.
