### ISSUE TITLE
Tag replacement limited by `Code` name

### ISSUE THREAD

**Issue by dc-almeida** [IAMconsortium/nomenclature#453]
In validating some workflow repos, I came across an error with illegal characters persisting even after disabling the check, meaning stray tags were present. Remembering some previous discussions, I noticed:
1) `Code` are only defined as containing tags if a tag is in their name (excluding other attributes)

https://github.com/dc-almeida/nomenclature/blob/b55aff5f5b78eceb2c939f8496fc0e366724c950/nomenclature/code.py#L87-L89

2) Tags are only replaced if the tag is also present in the `Code` name

https://github.com/dc-almeida/nomenclature/blob/b55aff5f5b78eceb2c939f8496fc0e366724c950/nomenclature/codelist.py#L112-L124

Should `Code` be defined as containing tags if tags are present in any attribute, and should tags be replaced even when not present in the `Code` name?
@phackstock @danielhuppmann

**Comment by phackstock** [comment]
A `Code` must contain **all tags** in the name otherwise the substitution does not make sense.
Consider the following example:

```yaml
- Variable 1:
  description: {template}
  unit: EJ/yr
```
with tags
```yaml
template:
    - first entry:
        description: description of first entry
    - second entry:
        description: description of second entry
```

would produce variables:

```yaml
- Variable 1:
  description: description of first entry
  unit: EJ/yr
- Variable 1:
  description: description of second entry
  unit: EJ/yr
```

which would violate the uniqueness constraint on the names of variables. In the above case Variable 1 is now ambiguous as we now have to different descriptions of one and the same variable.
