### ISSUE TITLE
Allow filtering of model mappings from external repositories

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/nomenclature#457]
Example:

```yaml
...
mappings:
  repository:
    name: common-definitions
    include:
      - MESSAGEix-GLOBIOM-GAINS 2.1-M-R12
```
