### ISSUE TITLE
Add a "range" validator

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#471]
In addition to the datavalidator-options of explicit upper & lower bounds and the value-plus-tolerance config, please add an option to specify a "range" keyword argument that sets both an upper and lower bound in one line, like used [here](https://github.com/IAMconsortium/common-definitions/blob/6bf8d67d2ddf8d7033a27ca6eb90f5917f58cdaf/definitions/variable/techno-economic/electricity-generation.yaml#L25)

```yaml
- Efficiency|Electricity|{Electricity Source}|*:
    description: Conversion efficiency per unit of primary energy of a newly installed
      plant to generate electricity from {Electricity Source} for a specific technology
    unit: "%"
    range: [ 0,100 ]
```
