### ISSUE TITLE
skip-region-aggregation: true is ignored for single consituent common regions

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/nomenclature#483]
I just encountered a case for a project where we had a variable where we decided to turn off region aggregation:

```yaml
- Power Generation Technologies|Coal fired:
    unit: '% Shares in Electricity production'
    description: Share of coal fired in electricity production
    skip-region-aggregation: true
...
``` 

in the model mapping we have two types of common regions, single- and multi-constituent:

```yaml
  - Reforming Economies (R5):
    - RUS
  - Asia (R5):
    - CHN
    - IND
    - KOR
    - IDN
```

in the processing results we now find no `Power Generation Technologies|Coal fired` for `Asia (R5)`. This is expected and desired since we turned regional aggregation off. 
For `Reforming Economies (R5)`, however, since the aggregation in this case is just a trivial renaming, we keep the `Power Generation Technologies|Coal fired` leading to some unexpected variables in some regions in the result.

@danielhuppmann, while I think this behavior is not technically wrong, I'd say it breaks the principle of least surprise and therefore we should also skip "region-aggregation" in single-constituent common regions, what do you think?

**Comment by danielhuppmann** [comment]
@dc-almeida can you please look at this issue in the next days?

**Comment by dc-almeida** [comment]
Looking at the current `RegionProcessor` implementation, it applies region processing by aggregation according to common regions and non-skipped variables, and then merges original input data already with common regions, and newly aggregated data. Processing single constituent regions the same way is a simple change, but this results in the edge case of a native region "renamed" to a common region with the same name retaining skipped variables (when the original DataFrame is filtered, it "interprets" the native region rows as common region because of the same name). In the test example below, `region_A` is such a case where the new "aggregate" will have skipped variables in the data, whereas `region_B` won't.

```yaml
model: model_b
common_regions:
  - region_A:
    - region_A
  - region_B:
    - region_b
```

Should this also be accounted for, ensuring even if the common region is the same name as the native region, in the aggregate DataFrame, the variable should disappear?
