### ISSUE TITLE
Add a `rename` option for the Aggregator

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#492]
The **Aggregator** class currently accepts only a config-mapping like 

```yaml
dimension: variable
aggregate:
  - Primary Energy:
    - Primary Energy|Coal
    - Primary Energy|Biomass
  - Final Energy:
    - Final Energy|Electricity
    - Final Energy|Heat
```

For some simple use cases (like the scenario-migration-tool by @lisahligono), we should also support a simple rename-feature, like
```yaml
dimension: unit
rename:
  - "?C": "°C"
  - "??C": "°C"
  - "?C-days": "°C-days"
```

[I was planning on doing this myself, but I realize that I won't get to it before the summer]

**Comment by dc-almeida** [comment]
Wouldn't it be more efficient to do:
```yaml
dimension: unit
rename:
  - "°C": ["?C" ,"??C"]
  - "°C-days": "?C-days"
```
This would avoid repeating the same target for each renaming candidate.
It would also keep the `target: components` pattern consistent with the `aggregate` field.
