### ISSUE TITLE
Validation of datetime format

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#54]
The openENTRANCE project uses subannual time resolution with the datetime format in two flavors:
- datetime format as a "time" column
- datetime format *without the year* in a "subannual" column plus a "year" column

Read the description in the [openentrance repository]( https://github.com/openENTRANCE/openentrance/tree/main/definitions/subannual#daily-or-hourly-resolution).

PR https://github.com/openENTRANCE/openentrance/pull/129/ added validation of the subannual format to the openentrance workflow. This feature should be migrated to this package once a second project requires support for subannual time resolution.

**Comment by danielhuppmann** [comment]
I think some configuration like the following would be useful in a `nomenclature.yaml`:

```yaml
- time:
    year: true
    datetime: true
```
or 
```yaml
- time:
    year: true
    datetime: UTC+01:00
```
to enfore the openentrance format for European time zone (see [here](https://github.com/openENTRANCE/openentrance/blob/61c346b9c3f5639e0e5174148adb31ce6f730b1f/workflow.py#L14)).

If `time` is given in the config, the validation should check that the `time` attribute of the **IamDataFrame** has the right format (including timezone-check of `datetime` is not simply true. The prototype for that is given in the openentrance workflow linked above.

**Comment by danielhuppmann** [comment]
Note that validation of "subannual" (categorical) timesteps already works simply by adding a folder `subannual` and activating it via `nomenclature.yaml`, see [here](https://github.com/openENTRANCE/openentrance/tree/main/definitions/subannual) in the openentrance project.

**Comment by dc-almeida** [comment]
To clarify, `nomenclature.yaml` would look something like this?
```yaml
dimensions:
  - region
  - variable
  - subannual
illegal_characters: [ ]
time:
  year: true
  datetime: UTC+01:00
```

**Comment by danielhuppmann** [comment]
Correct, this would allow all three pyam-supported time domains.

**Comment by dc-almeida** [comment]
Would it be clearer for users if we call it `timezone` instead of `datetime`?

**Comment by danielhuppmann** [comment]
Well… There are three types of time format in pyam and ixmp4 called “year”, “subannual” and “datetime”, so I would keep the naming in nomenclature consistent. But if you think that it would be easier to specify the configuration explicitly, we could also do a more elaborate approach like
```yaml
time:
  datetime: true
```
to accept any datetime timeseries data or

```yaml
time:
  datetime:
    timezone: UTC+01:00
```
to only allow datetime in CET.

**Comment by dc-almeida** [comment]
> [...] validation of the subannual format to the openentrance workflow. This feature should be migrated to this package [...]

So validate cases where the data looks like this:

| subannual | 2015 | 2020 | 2025 | ... |
|---|---|---|---|---|
| ... | ... | ... | ... | ... |

```yaml
time:
  year: true
  datetime: true | UTC±HH:MM
```

In case of `datetime: false` (or omitted), it's the default yearly data format, and if `year: false` and `datetime: true | UTC±HH:MM`, it would be:

| time | value | 
|---|---|
| ... | ... |

Should validation for this long format be implemented too?
