### ISSUE TITLE
Create custom GitHub action for validating projects

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/nomenclature#58]
As a number of projects use the nomenclature package in form of a GitHub action for validation of their data structure definitions and their region mappings it would be nice to add a GitHub action to this repository.
This GitHub action can the be used directly in the various projects.

This is what this action might look like:
```yaml

# This workflow validates that the project is consistent with the nomenclature
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Validate the project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

jobs:
  project-validation:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Run the nomenclature project validation
      run: nomenclature validate-project .
```
