### ISSUE TITLE
Perform aggregation and rename

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#82]
In the ECEMF project, we came across the issue where several region-aggregation configurations for the same variable should be performed. The particular use case: for carbon prices, it can be beneficial to compute weighted averages using alternative weights:

 - the "obvious" solution to use CO2 emissions as weights, but this can lead to strange results if weights go negative (see https://github.com/IAMconsortium/pyam/issues/446)
 - other weights like Final Energy or GDP, which cannot go negative 

When using alternative weights, it would be helpful to "remember" the alternative weight (and make it explicit) by changing the variable name, so when region-aggregating the "Price|Carbon" variable with "Final Energy" as weight, the resulting timeseries variable could be renamed to  "Price|Carbon (weighted by Final Energy)".

One solution to implement this would be to add a "rename" argument to the variable attributes, e.g.

```yaml
- Price|Carbon:
    description: Price of carbon (for regional aggregrates the weighted price of carbon
        by subregion should be used)
    unit: [EUR_2020/t CO2, USD_2010/t CO2]
    weight: Final Energy
    rename: Price|Carbon (weighted by Final Energy)
```
