### ISSUE TITLE
Allow multiple "model" values in a region-mapping file

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#84]
The "model" attribute in a region-processing mapping-file currently only takes a string value. It would be beneficial to allow this to be a list so that one region-mapping can be used to several (minor/patch) versions of a model.

So the extended use of the region-mapping file could look like the following (based on https://github.com/openENTRANCE/openentrance/pull/148):

```yaml
model:
  -  OSeMBE v1.0.0
  -  OSeMBE v1.1.0
  -  OSeMBE v1.2.0
native_regions:
  - AUT: OSeMBE v1|AUT
  ...

 common_regions:
   - EU27:
     - AUT
     ...
```

or

```yaml
model:
  -  OSeMBE v1.0.0
  -  OSeMBE v1.0.1
  -  OSeMBE v1.0.2
native_regions:
  - AUT: OSeMBE v1.0|AUT
  ...

 common_regions:
   - EU27:
     - AUT
     ...
```
depending on the likelihood of region-changes over the model versions
